import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SvgImage from "@/assets/Vector.svg";
import SvgImage1 from "@/assets/Vector1.svg";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          minHeight: "90vh",
          height: "100%",
          backgroundColor: "#093545",
        }}
      >
        {children}
        <div
          style={{
            width: "100%",
            height: "15%",
            position: "fixed",
            bottom: 0,
            zIndex: 999,
          }}
        >
          <Image
            alt="Mountains"
            src={SvgImage}
            layout="fill"
            style={{ objectFit: "contain" }}
          />
        </div>
        <div
          style={{
            width: "100%",
            height: "15%",
            position: "fixed",
            bottom: 0,
            zIndex: 999,
          }}
        >
          <Image
            alt="Mountains"
            src={SvgImage1}
            layout="fill"
            style={{ objectFit: "contain" }}
          />
        </div>
      </body>
    </html>
  );
}
